import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JotaiProvider } from "@/providers/jotai-provider";
import { Modals } from "@/components/modals";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background text-foreground antialiased max-w-full overflow-x-hidden`}
      ><JotaiProvider>
        <Modals/>
        {children}
      </JotaiProvider>
      </body>
    </html>
  );
}
