import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/auth";
import { ThemeProvider } from "@/providers/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>

      <body
        className={`min-h-screen bg-background text-foreground antialiased max-w-full overflow-x-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
          </AuthProvider>

        </ThemeProvider>
      </body>

    </html>
  );
}
